import{a as E,S as q,i as f}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const v="45031558-a09c4143603aaf44ec68d2085",$="https://pixabay.com/api/";async function m(r,t=1){const n=`${$}?key=${v}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`;try{const s=await E.get(n);if(s.status!==200)throw new Error("Failed to fetch images");return s.data}catch(s){throw console.error("Error fetching images:",s),s}}let d;function I(){const r=document.querySelector(".gallery");r.innerHTML=""}function g(r){const t=document.querySelector(".gallery"),n=r.map(({webformatURL:e,largeImageURL:o,tags:i,likes:L,views:w,comments:S,downloads:b})=>`
      <a class="gallery-item" href="${o}">
        <img src="${e}" alt="${i}" loading="lazy" />
        <div class="info info-wrap">
          <p class="info-item info-item-css"><b>Likes:</b> ${L}</p>
          <p class="info-item info-item-css"><b>Views:</b> ${w}</p>
          <p class="info-item info-item-css"><b>Comments:</b> ${S}</p>
          <p class="info-item info-item-css"><b>Downloads:</b> ${b}</p>
        </div>
      </a>
    `).join("");t.insertAdjacentHTML("beforeend",n),d?d.refresh():d=new q(".gallery a"),document.querySelectorAll(".gallery-item img").forEach(e=>{e.addEventListener("error",()=>{e.src="https://via.placeholder.com/640x480?text=Image+Not+Found"})})}function P(){f.info({title:"Sorry",message:"There are no images matching your search query. Please try again!"})}function y(){document.querySelector(".loader").classList.remove("hidden")}function h(){document.querySelector(".loader").classList.add("hidden")}function O(){f.info({title:"End of Results",message:"Sorry, but you've reached the end of search results."})}const p=document.querySelector("#search-form"),x=p.querySelector("input");document.querySelector(".gallery");document.querySelector(".loader");const c=document.querySelector(".load-more");let l="",a=1,u=0;c.classList.add("hidden");p.addEventListener("submit",async r=>{if(r.preventDefault(),l=x.value.trim(),!!l){a=1,I(),c.classList.add("hidden"),y();try{const t=await m(l,a);u=t.totalHits,t.hits.length===0?P():(g(t.hits),u>15&&c.classList.remove("hidden"))}catch(t){console.error("Error:",t),iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{h()}}});c.addEventListener("click",async()=>{a+=1,y();try{const r=await m(l,a);g(r.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),a*15>=u&&(c.classList.add("hidden"),O())}catch(r){console.error("Error:",r),iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{h()}});
//# sourceMappingURL=commonHelpers.js.map
